version: "3"
services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      TZ: "Europe/Istanbul"
      PORT: 8081
      JWT_TOKEN_EXP_SECOND: 86400
      JWT_TOKEN_MAX_REFRESH_SECOND: 86400
      JWT_TOKEN_SECRET: "R1BYcTVXVGNDU2JmWHVnZ1lnN0FKeGR3cU1RUU45QXV4SDJONFZ3ckhwS1N0ZjNCYVkzZ0F4RVBSS1UzRENwRw=="
      TOKEN_IDENTITY_KEY: "id"
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DB: user-db
    ports:
      - "8081:8081"

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      TZ: "Europe/Istanbul"
      MYSQL_DATABASE: user-db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
